[package]
name = "raw-seeders"
version = "0.0.0-dev"
authors = ["Tamme Schichler <tamme@schichler.dev>"]
edition = "2018"
publish = false

[dependencies]
arrayvec = "0.5.1"
cast = "0.2.3"
encoding = "0.2.33"
log = "0.4.11"
serde = "1.0.115"
serde-seeded = { path = "../serde-seeded" }
wyz = "0.2.0"
